server:
  port: 7700
#  ≈‰÷√rabbitµ√µÿ÷∑
spring:
  rabbitmq:
    host: 192.168.174.130
    port: 5672
    username: guest
    password: guest
  datasource:
    url: jdbc:mysql://192.168.174.130:3306/dm_zipkin?useUnicode=true&characterEncoding=gbk&zeroDateTimeBehavior=convertToNull
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
zipkin:
  storage:
      type : mysql


